# Netlify & Github Backend
backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: development
  repo: AIGAdc/dcdesignweek.org-11ty

# Enable/Disable Editorial Workflow
#publish_mode: editorial_workflow

# Enable/Disable Local Backend. Use the command "npx netlify-cms-proxy-server" to use Netlify CMS locally
local_backend: true

# Media Folders
media_folder: "source/static/images"
public_folder: "/static/images"

# Collection Settings
collections:
  # Pages allows for easier editing of pages on the site
  - label: "Pages"
    name: "pages"
    # Defaults to "true". Must be set to "false" to turn the preview off completely.
    editor:
      preview: false
    # Define the pages that should be visible inside the CMS.
    files:
      - label: "About"
        name: "about"
        file: "source/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Accessibility"
        name: "accessibility"
        file: "source/pages/accessibility.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Events"
        name: "events"
        file: "source/pages/events.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "FAQs"
        name: "faqs"
        file: "source/pages/faqs.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Home"
        name: "home"
        file: "source/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Makers"
        name: "makers"
        file: "source/pages/makers.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Page Content", name: "pageContent", widget: "markdown", required: false }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }

  - label: "Events"
    name: "events"
    folder: "source/events"
    create: true
    slug: "{{slug}}" # Filename template, e.g., title.md
    # Defaults to "true". Must be set to "false" to turn the preview off completely.
    editor:
      preview: false
    fields:
      - { label: "Title", hint: "Required. Provide the event title.", name: "title", widget: "string" }
      - { label: "Description", hint: "Required. Provide an event description.", name: "description", widget: "string"}
      - { label: "Start Date", hint: "Required. Provide the event start time.", name: "startDate", widget: "datetime"}
      - { label: "End Date", hint: "Required. Provide the event end time.", name: "endDate", widget: "datetime"}
      - { label: "Image", hint: "Required. Provide the image that will be used in the event header of event page and event card.", name: "image", widget: "image" }
      - { label: "Image Alt", hint: "Required. Provide descriptive text of image used above.", name: "imageALT", widget: "string" }
      - label: Tickets
        name: tickets
        hint: "This field will allow an Editor, to add tickets to the event page. There are two options 'Member' and 'Non-Member'. Once you have selected the button type you can then provide the button label and button url."
        widget: list
        fields:
          - {label: Button Type, name: buttonType, widget: select, options: ["Member", "Non-Member"] }
          - {label: Button Label, name: buttonLabel, widget: string}
          - {label: Button URL, name: buttonURL, widget: string}
      - label: Status
        name: status
        widget: list
        fields:
          - {label: Status Type, name: statusType, widget: select, options: ["Featured on Home", "Featured on Events", "Has Occurred"] }
          - {label: Status Label, name: statusLabel, widget: string}
      - { label: "Details", name: "details", widget: "markdown", required: false }
      - { label: "How to Prepare", name: "preparation", widget: "markdown", required: false }
      - { label: "a11y", name: "a11y", widget: "markdown", required: false }
      - label: Speaker
        name: speaker
        allow_add: true
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Pronunciation, name: pronunciation, widget: string}
          - {label: Pronouns, name: pronouns, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Alt, name: imageALT, widget: string}
          - {label: Websites, name: websites, widget: markdown, required: false, sanitize_preview: true}

  - label: "Data Files"
    name: "settings"
    description: Files that provide global data to be re-used across the DCDW website.
    # Defaults to "true". Must be set to "false" to turn the preview off completely.
    editor:
      preview: false
    files:
      - label: "Accessibility"
        name: "accessibility"
        file: "source/_data/accessibility.yaml"
        fields:
          - label: Global
            name: global
            allow_add: false
            collapsed: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: markdown }
              - { label: buttonURL, name: buttonURL, widget: string }
              - { label: buttonLabel, name: buttonLabel, widget: string }
              - label: "Button Background Color"
                name: "buttonBGColor"
                widget: select
                options: ["background-color-black", "background-color-white", "background-color-cream", "background-color-teal", "background-color-valencia", "background-color-zodiac"]
              - label: "Button Text Color"
                name: "buttonTextColor"
                widget: select
                options: ["color-black", "color-white", "color-cream", "color-teal", "color-valencia", "color-zodiac"]
            widget: list
      - label: "Events"
        name: "events"
        file: "source/_data/events.yaml"
        fields:
          - label: Global
            name: global
            allow_add: false
            collapsed: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: markdown }
              - { label: buttonURL, name: buttonURL, widget: string }
              - { label: buttonLabel, name: buttonLabel, widget: string }
              - label: "Button Background Color"
                name: "buttonBGColor"
                widget: select
                options: ["background-color-black", "background-color-white", "background-color-cream", "background-color-teal", "background-color-valencia", "background-color-zodiac"]
              - label: "Button Text Color"
                name: "buttonTextColor"
                widget: select
                options: ["color-black", "color-white", "color-cream", "color-teal", "color-valencia", "color-zodiac"]
            widget: list
      - label: "FAQs"
        name: "faqs"
        file: "source/_data/faqs.yaml"
        fields:
          - label: Global
            name: global
            allow_add: false
            collapsed: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: markdown }
              - { label: buttonURL, name: buttonURL, widget: string }
              - { label: buttonLabel, name: buttonLabel, widget: string }
              - label: "Button Background Color"
                name: "buttonBGColor"
                widget: select
                options: ["background-color-black", "background-color-white", "background-color-cream", "background-color-teal", "background-color-valencia", "background-color-zodiac"]
              - label: "Button Text Color"
                name: "buttonTextColor"
                widget: select
                options: ["color-black", "color-white", "color-cream", "color-teal", "color-valencia", "color-zodiac"]
            widget: list
      - label: "Filters"
        name: "filters"
        file: "source/_data/filters.yaml"
        fields:
          - label: Global
            name: global
            allow_add: false
            collapsed: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: markdown }
              - { label: buttonURL, name: buttonURL, widget: string }
              - { label: buttonLabel, name: buttonLabel, widget: string }
              - label: "Button Background Color"
                name: "buttonBGColor"
                widget: select
                options: ["background-color-black", "background-color-white", "background-color-cream", "background-color-teal", "background-color-valencia", "background-color-zodiac"]
              - label: "Button Text Color"
                name: "buttonTextColor"
                widget: select
                options: ["color-black", "color-white", "color-cream", "color-teal", "color-valencia", "color-zodiac"]
            widget: list
      - label: "Staff"
        name: "staff"
        file: "source/_data/staff.yaml"
        fields:
          - label: Global
            name: global
            allow_add: false
            collapsed: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: markdown }
              - { label: buttonURL, name: buttonURL, widget: string }
              - { label: buttonLabel, name: buttonLabel, widget: string }
              - label: "Button Background Color"
                name: "buttonBGColor"
                widget: select
                options: ["background-color-black", "background-color-white", "background-color-cream", "background-color-teal", "background-color-valencia", "background-color-zodiac"]
              - label: "Button Text Color"
                name: "buttonTextColor"
                widget: select
                options: ["color-black", "color-white", "color-cream", "color-teal", "color-valencia", "color-zodiac"]
            widget: list
      - label: "Settings"
        name: "settings"
        file: "source/_data/settings.yaml"
        fields:
          - label: "Primary Navigation Links"
            name: "primaryNavLinks"
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Enabled, name: enabled, widget: boolean }
      - label: "Sponsors"
        name: "sponsors"
        file: "source/_data/sponsors.yaml"
        fields:
          - label: Global
            name: links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: URL, name: url, widget: string }
              - { label: Label, name: label, widget: string }
              - { label: Enabled, name: enabled, widget: boolean }
      - label: "Subscription"
        name: "subscription"
        file: "source/_data/subscription.yaml"
        fields:
          - label: Global
            name: links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: URL, name: url, widget: string }
              - { label: Label, name: label, widget: string }
              - { label: Enabled, name: enabled, widget: boolean }
