primaryNavLinks:
  - title: Events
    url: /events/
    external: false
    enabled: true
  - title: About
    url: /about/
    external: false
    enabled: true
  - title: Committee
    url: /committee/
    external: false
    enabled: true
  - title: faq
    url: /faq/
    external: false
    enabled: True
  - title: Makers
    url: /makers/
    external: false
    enabled: false
  # - title: Airtable QA
  #   url: https://airtable.com/shrdjeB71EVPvMd2P
  #   external: true
  #   enabled: True
secondaryNavLinks:
  - title: Contact
    url: mailto:designweek@dc.aiga.org
    external: false
    enabled: true
  - title: Accessibility
    url: /accessibility/
    external: false
    enabled: true
  - title: Colophon
    url: /colophon/
    external: false
    enabled: false
  - title: Mission
    url: https://dc.aiga.org/about-us/mission/
    external: true
    enabled: true
